CREATE TABLE IF NOT EXISTS fish (
  id INTEGER PRIMARY KEY,
  user_email TEXT NOT NULL,
  name TEXT NOT NULL, -- always "Fish"
  caught_at TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS players (
  user_email TEXT PRIMARY KEY,
  xp INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 1,
  gold INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
);